<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Unit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="Testing.Bdd" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain.Notifications\Domain.Notifications.csproj" />
  </ItemGroup>
</Project>