<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Tickets\Messages.Tickets\Messages.Tickets.csproj" />
        <ProjectReference Include="..\Application.Events\Application.Events.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit"/>
    </ItemGroup>

</Project>
