<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>Integration</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\CommonLibraries\Testing\Testing.csproj" />
    <ProjectReference Include="..\..\..\Database\Migrations\Migrations.csproj" />
    <ProjectReference Include="..\Controllers.Notifications\Controllers.Notifications.csproj" />
    <ProjectReference Include="..\Infrastructure.Notifications\Infrastructure.Notifications.csproj" />
    <ProjectReference Include="..\Messages.Notifications\Messages.Notifications.csproj" />
    <ProjectReference Include="..\Messaging.Notifications\Messaging.Notifications.csproj" />
    <ProjectReference Include="..\..\Tickets\Messages.Tickets\Messages.Tickets.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="NUnit" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="NotificationController.steps.cs">
      <DependentUpon>NotificationController.specs.cs</DependentUpon>
    </Compile>
    <Compile Update="TicketPurchasedConsumer.steps.cs">
      <DependentUpon>TicketPurchasedConsumer.specs.cs</DependentUpon>
    </Compile>
    <Compile Update="Consumer\TicketPurchasedConsumer.steps.cs">
      <DependentUpon>TicketPurchasedConsumer.specs.cs</DependentUpon>
    </Compile>
    <Compile Update="Notifications\GetNotifications.steps.cs">
      <DependentUpon>GetNotifications.specs.cs</DependentUpon>
    </Compile>
    <Compile Update="Notifications\GetUnreadCount.steps.cs">
      <DependentUpon>GetUnreadCount.specs.cs</DependentUpon>
    </Compile>
    <Compile Update="Notifications\MarkNotificationAsRead.steps.cs">
      <DependentUpon>MarkNotificationAsRead.specs.cs</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>