<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <RootNamespace>Application</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\CommonLibraries\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="Testing.Bdd" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="ClaimsPrincipalExtensions.steps.cs">
            <DependentUpon>ClaimsPrincipalExtensions.specs.cs</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>