<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application.Notifications\Application.Notifications.csproj" />
    <ProjectReference Include="..\Domain.Notifications\Domain.Notifications.csproj" />
    <ProjectReference Include="..\..\..\CommonLibraries\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Messaging.Notifications\Messaging.Notifications.csproj" />
  </ItemGroup>
</Project>