<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <IsPackable>true</IsPackable>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <NoWarn>RS1036;RS2008;RS1041</NoWarn>
        <RootNamespace>Architecture.Events</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" />
      <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    </ItemGroup>

</Project>
