<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Keycloak.Users\Domain.Keycloak\Domain.Keycloak.csproj" />
      <ProjectReference Include="..\..\Keycloak.Users\Keycloak.Domain\Domain.Keycloak\Domain.Keycloak.csproj" />
      <ProjectReference Include="..\..\Keycloak.Users\Infrastructure.Keycloak\Infrastructure.Keycloak.csproj" />
      <ProjectReference Include="..\Application.Events\Application.Events.csproj" />
      <ProjectReference Include="..\Domain.Events\Domain.Events.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Mvc"/>
    </ItemGroup>

</Project>
