<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Events\Messages.Events\Messages.Events.csproj" />
        <ProjectReference Include="..\..\Keycloak.Users\Messages.Keycloak.Users\Messages.Keycloak.Users.csproj" />
        <ProjectReference Include="..\Application.Tickets\Application.Tickets.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit"/>
        <PackageReference Include="MassTransit.RabbitMQ" />
    </ItemGroup>

</Project>
