apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  namespace: ticketbuddy
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migrations
        image: ticketbuddy-migrations:local
        imagePullPolicy: Never
        env:
        - name: ENVIRONMENT
          value: Development
