<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit.EntityFrameworkCore"/>
        <PackageReference Include="StackExchange.Redis"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application.Tickets\Application.Tickets.csproj" />
      <ProjectReference Include="..\Domain.Tickets\Domain.Tickets.csproj" />
      <ProjectReference Include="..\..\..\CommonLibraries\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\Messaging.Tickets\Messaging.Tickets.csproj" />
    </ItemGroup>

</Project>
