<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
        <RootNamespace>Integration</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\CommonLibraries\Testing\Testing.csproj" />
      <ProjectReference Include="..\..\..\Database\Migrations\Migrations.csproj" />
      <ProjectReference Include="..\Controllers.Events\Controllers.Events.csproj" />
      <ProjectReference Include="..\Infrastructure.Events\Infrastructure.Events.csproj" />
      <ProjectReference Include="..\Messages.Events\Messages.Events.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NUnit3TestAdapter"/>
        <PackageReference Include="NUnit"/>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="EventController.steps.cs">
        <DependentUpon>EventController.specs.cs</DependentUpon>
      </Compile>
      <Compile Update="VenueController.steps.cs">
        <DependentUpon>VenueController.specs.cs</DependentUpon>
      </Compile>
      <Compile Update="Events\CreateEvent.steps.cs">
        <DependentUpon>CreateEvent.specs.cs</DependentUpon>
      </Compile>
      <Compile Update="Events\EventSoldOutConsumer.steps.cs">
        <DependentUpon>EventSoldOutConsumer.specs.cs</DependentUpon>
      </Compile>
      <Compile Update="Events\GetEventById.steps.cs">
        <DependentUpon>GetEventById.specs.cs</DependentUpon>
      </Compile>
      <Compile Update="Events\GetEvents.steps.cs">
        <DependentUpon>GetEvents.specs.cs</DependentUpon>
      </Compile>
      <Compile Update="Events\UpdateEvent.steps.cs">
        <DependentUpon>UpdateEvent.specs.cs</DependentUpon>
      </Compile>
      <Compile Update="Venues\CreateVenue.steps.cs">
        <DependentUpon>CreateVenue.specs.cs</DependentUpon>
      </Compile>
      <Compile Update="Venues\GetVenues.steps.cs">
        <DependentUpon>GetVenues.specs.cs</DependentUpon>
      </Compile>
      <Compile Update="Venues\UpdateVenue.steps.cs">
        <DependentUpon>UpdateVenue.specs.cs</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
